// AUTO-GENERATED by scripts/gen-nav.mjs. Do not edit by hand.
import type { IconName } from "./icon-utils"

export type NavEntry = {
  title: string
  slug: string
  iconName: IconName
}

export const BLOG_NAV: NavEntry[] = [
  { title: "hands_on_llms.epub", slug: "hands-on-large-language-models-alammar", iconName: "epub" },
  { title: "coding_with_ai_traversy.ai", slug: "coding-with-ai-traversy", iconName: "claude" },
  { title: "claude_code_in_action.ai", slug: "claude-code-in-action", iconName: "claude" },
  { title: "designing_data_intensive_apps.epub", slug: "designing-data-intensive-applications-kleppmann", iconName: "epub" },
  { title: "soft_skills.epub", slug: "soft-skills-sonmez", iconName: "epub" },
  { title: "fluent_python.epub", slug: "fluent-python-ramalho", iconName: "epub" },
  { title: "exercism.py", slug: "exercism", iconName: "python" },
  { title: "design_patterns_shvets.epub", slug: "design-patterns-shvets", iconName: "epub" },
  { title: "full_stack_supplementary.ts", slug: "full-stack-open-supplementary", iconName: "typeScriptAlt" },
  { title: "pentester_course.ts", slug: "pentester-course", iconName: "typeScriptAlt" },
  { title: "full_stack_open_core.ts", slug: "full-stack-open-core", iconName: "typeScriptAlt" },
  { title: "odin_foundation_course.ts", slug: "odin-foundation-course", iconName: "typeScriptAlt" },
]

export const SIDE_PROJECTS_NAV: NavEntry[] = [
  { title: "brain.karolkarnas.com", slug: "brain-karolkarnas-com", iconName: "python" },
  { title: "cardpiper.com", slug: "card-piper-com", iconName: "nestJs" },
  { title: "karnas.dev", slug: "karnas-dev", iconName: "nextJs" },
  { title: "ilustrografia.com", slug: "ilustrografia-com", iconName: "react" },
]

export const PROFESSIONAL_PROJECTS_NAV: NavEntry[] = [
  { title: "dms.py", slug: "dms-housing-authority", iconName: "python" },
  { title: "data_bid_machine.py", slug: "data-bid-machine", iconName: "python" },
]
