#!/usr/bin/env node
import fs from "node:fs"
import path from "node:path"
import matter from "gray-matter"

const ROOT = process.cwd()
const OUTPUT = path.join(ROOT, "src/utils/generated-nav.ts")

const SOURCES = [
  {
    exportName: "BLOG_NAV",
    typeName: "BlogNavEntry",
    dir: "_posts",
    routePrefix: "/blog",
  },
  {
    exportName: "SIDE_PROJECTS_NAV",
    typeName: "SideProjectNavEntry",
    dir: "_projects",
    routePrefix: "/side-projects",
  },
  {
    exportName: "PROFESSIONAL_PROJECTS_NAV",
    typeName: "ProfessionalProjectNavEntry",
    dir: "_professional",
    routePrefix: "/professional-projects",
  },
]

function readEntries(dir) {
  const full = path.join(ROOT, dir)
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith(".md"))
    .map((file) => {
      const slug = file.replace(/\.md$/, "")
      const raw = fs.readFileSync(path.join(full, file), "utf8")
      const { data } = matter(raw)
      return {
        slug,
        date: data.date,
        nav_title: data.nav_title,
        nav_icon: data.nav_icon,
      }
    })
    .filter((e) => {
      if (!e.nav_title || !e.nav_icon) {
        console.warn(
          `[gen-nav] skipping ${dir}/${e.slug} — missing nav_title or nav_icon`,
        )
        return false
      }
      return true
    })
    .sort((a, b) => (a.date > b.date ? -1 : 1))
}

const blocks = SOURCES.map((source) => {
  const entries = readEntries(source.dir)
  const body = entries
    .map(
      (e) =>
        `  { title: ${JSON.stringify(e.nav_title)}, slug: ${JSON.stringify(e.slug)}, iconName: ${JSON.stringify(e.nav_icon)} },`,
    )
    .join("\n")
  console.log(
    `[gen-nav] ${source.exportName}: ${entries.length} entries from ${source.dir}`,
  )
  return { source, body, count: entries.length }
})

const out = `// AUTO-GENERATED by scripts/gen-nav.mjs. Do not edit by hand.
import type { IconName } from "./icon-utils"

export type NavEntry = {
  title: string
  slug: string
  iconName: IconName
}

${blocks
  .map(
    ({ source, body }) =>
      `export const ${source.exportName}: NavEntry[] = [\n${body}\n]\n`,
  )
  .join("\n")}`

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true })
fs.writeFileSync(OUTPUT, out)
console.log(`[gen-nav] wrote ${OUTPUT}`)
